version: '3.8'

services:
  ncat:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - storage:/app/storage
      - logs:/app/logs
    restart: unless-stopped

volumes:
  storage:
    driver: local
  logs:
    driver: local 